### ISSUE TITLE
Tables in steps

### ISSUE THREAD

**Issue by Eernie** [Eernie/JMoribus#1]

**Comment by r0b3rtk** [comment]
Possible solution to implementing table support:

Use the tab character (\t) as separator character for table cells (these are not visible so don't clutter the view on the story for the user). Since tabs will probably be used for table-layout purposes as well the algorithm needs to filter out any sequential tab characters.

With `String.split('\t')` we can then separate the cells (per table row) in an array. This needs to be done for every row in the table.

Disadvantage of this approach is that it is not markdown-compatible. Table parsing could be placed in different strategies using the strategy pattern (e.g. MarkDownTableParserStrategy, BBCodeTableParserStrategy), so that different table formats can be supported, and displayed in the same way to the user.

**Comment by r0b3rtk** [comment]
Added a factory for returning the correct table parser. Currently only tab spaced tables are supported.

Table support should be added for
- Parametrized scenario's (i.e. one or more variables in the scenario (enclosed by < and >) must be substituted with data in the examples table, and the scenario must be run for every row in the table)
- Using tables in teststeps

**Comment by Eernie** [comment]
Changed the grammar for tables. It's The grammar accepts the examples tables now and the table in a step.
The Listener is seposed to be implemented for the tables.
